# .readthedocs.yaml
version: 2

# ───────────────────────────── Build system ────────────────────────────────
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# ───────────────────────────── Python env ───────────────────────────────────
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true
